### ISSUE TITLE
[BE] ToDo API 코드 리뷰 적용

### ISSUE THREAD

**Issue by 2heekeon** [CodeQuartette/myTime#63]
- [x] controller layer에서 Entity를 Response로 변경하는 작업 진행
- [x]  update하고 수정된 객체를 return을 해주지 않는데, 수정된 객체를 return 하도록 개발.
- [x] @ RequestMapping 어노테이션을 사용
- [x] getToDoById 와 getToDoByDate 컨트롤러 병합.
- [x] import에 올라가져야할 부분이 메소드로 수정 + 불필요 메소드 삭제
- [x] 날짜 별 조회 서비스 로직을 객체지향적으로 변경.
